<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <TargetPlatform>Windows</TargetPlatform>
        <TargetPlatformIdentifier>Windows</TargetPlatformIdentifier>
        <UserSecretsId>ValleAosta3D-OpenTopography</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BitMiracle.LibTiff.NET" Version="2.4.660" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.10" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.10" />
        <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.10" />
        <PackageReference Include="System.Drawing.Common" Version="10.0.10" />
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
